Repository cloudfoundry/docs-buildpacks, pull requests merged in 2020-02, with the labels that each got.

#261 Fix typos on buildpacks documentation
  developing-buildpacks.html.md.erb
Labels: in progress

#262 Cnb migration
  node/node-migration.md.erb
  nodejs-cnb/index.html.md.erb
Labels: unscheduled

#263 remove docs for NODE_PATH, as it is no longer used
  nodejs-cnb/index.html.md.erb
Labels: in progress

#265 Contribute CF documentation for the PHP CNB
  php-cnb/index.html.md.erb
  php-cnb/php-composer.html.md.erb
  php-cnb/php-config.html.md.erb
  php-cnb/php-migration.html.md.erb
  php-cnb/php-sessions.html.md.erb
  php-cnb/php-usage.html.md.erb
Labels: scheduled
